### ISSUE TITLE
Error serializing Avro message

### ISSUE THREAD

**Issue by cretok** [mravi/kafka-cdc-hbase#1]
Hello~
When I run "kafka-avro-console-producer" and send message, ERROR serializing Avro message occurs.
I used your original source, I just edited hadoop version from 2.6.0 to 2.7.0 
Please check this error message.

> error meesage
> [root@server002 confluent]# bin/kafka-avro-console-producer --broker-list localhost:9092 --topic connectTest --property value.schema='{"type":"record","name":"record","fields":[{"name":"id","type":"int"}, {"name":"name", "type": "string"}]}'
> /bin/bash: warning: setlocale: LC_ALL: cannot change locale (ko_KR.UTF-8)
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (ko_KR.UTF-8)
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/sepDir/ossFileDownload/confluent-2.0.1/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/sepDir/ossFileDownload/confluent-2.0.1/share/java/confluent-common/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/sepDir/ossFileDownload/confluent-2.0.1/share/java/schema-registry/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
> {"id": 1, "name": "foo"}
> **org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')**
>  at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@359df09a; line: 1, column: 2]
>         at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
>         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
>         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2485)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
>         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3604)
>         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549)
>         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2650)
>         at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:155)
>         at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:174)
>         at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:225)
>         at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:217)
>         at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:212)
>         at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:57)
>         at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:89)
>         at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:50)
>         at io.confluent.kafka.formatter.AvroMessageReader.readMessage(AvroMessageReader.java:157)
>         at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:56)
>         at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)

`version information on Pom.xml`
        hbase.version>1.2.0</hbase.version>
        hadoop.version>2.7.0</hadoop.version>
        kafka.version>0.9.0.0</kafka.version>
        junit.version>4.12</junit.version>
        hadoop.mvn.version>2.7.1</hadoop.mvn.version>
        guava.version>16.0</guava.version>
        confluent.version>2.0.0</confluent.version>

`hbase-sink.properties`
name=kafka-cdc-hbase
connector.class=io.svectors.hbase.sink.HBaseSinkConnector
tasks.max=1
topics=connectTest
zookeeper.quorum=localhost:2181
event.parser.class=io.svectors.hbase.parser.AvroEventParser

hbase.connectTest.rowkey.columns=id
hbase.connectTest.rowkey.delimiter=|
hbase.connectTest.family=f1

**Comment by cretok** [comment]
This error is related with port problem. The confluent default port is 8081, but I changed the port to 8085 because other service already use 8081 port. I modified the "DEFAULT_SCHEMA_REGISTRY_URL" value of "kafka-avro-console-producer" file, then it runs successfully.
