### ISSUE TITLE
Encountered NPE when  HBase sink is started

### ISSUE THREAD

**Issue by Nilkanthpatel04** [mravi/kafka-cdc-hbase#3]
Used HBase 1.2.4 and confluent-3.0.0 (oss)
When starting a HBase sink encountered following error

[2017-01-04 17:58:31,841] INFO HBaseSinkConfig values: 
	event.parser.class = io.svectors.hbase.parser.AvroEventParser
	zookeeper.quorum = localhost:2181
 (io.svectors.hbase.config.HBaseSinkConfig:165)
[2017-01-04 17:58:32,016] INFO Sink task org.apache.kafka.connect.runtime.WorkerSinkTask@670b160d finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:155)
[2017-01-04 17:58:32,476] ERROR Task kafka-cdc-hbase-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:302)
[2017-01-04 17:58:32,476] ERROR Task is being killed and will not recover until manually restarted: (org.apache.kafka.connect.runtime.WorkerSinkTask:303)
java.lang.NullPointerException
	at org.apache.hadoop.hbase.client.Put.<init>(Put.java:68)
	at org.apache.hadoop.hbase.client.Put.<init>(Put.java:58)
	at io.svectors.hbase.util.ToPutFunction.apply(ToPutFunction.java:67)
	at io.svectors.hbase.sink.HBaseSinkTask.lambda$null$0(HBaseSinkTask.java:77)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.svectors.hbase.sink.HBaseSinkTask.lambda$put$1(HBaseSinkTask.java:77)
	at java.util.stream.Collectors.lambda$toMap$215(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.svectors.hbase.sink.HBaseSinkTask.put(HBaseSinkTask.java:76)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:280)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
	at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
[2017-01-04 17:58:32,479] ERROR Thread WorkerSinkTask-kafka-cdc-hbase-0 exiting with uncaught exception:  (org.apache.kafka.connect.util.ShutdownableThread:84)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
	at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Exception in thread "WorkerSinkTask-kafka-cdc-hbase-0" org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
	at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)

**Comment by Nilkanthpatel04** [comment]
@mravi any inputs on my issue?

**Comment by Loernl** [comment]
Same problem I had，Are you making any progress？

**Comment by mravi** [comment]
@Loernl I was a bit passive earlier.  I have some free cycles now, will look into it and respond.

**Comment by Loernl** [comment]
ok,thanks,i will wait you feedback.
